//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodigoRecuperacion
    {
        public string codigo { get; set; }
        public long usuario { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
