//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento_X_Cliente
    {
        public int departamentoId { get; set; }
        public int clienteId { get; set; }
        public Nullable<int> cant_departamentos { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Departamentos Departamentos { get; set; }
    }
}
