//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoSMTP
    {
        public string Correo { get; set; }
        public string Password { get; set; }
        public string ServidorSMTP { get; set; }
        public int Puerto { get; set; }
        public string SSL { get; set; }
    }
}
